# Site settings
title: Pedantic platitudes

baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: I am a floating head

# Social icons
twitter: backdeluca
linkedin: arturbackdeluca
github: artur-deluca
email: arturbackdeluca@gmail.com

footer:

# Build settings
markdown: kramdown
